name: iss-preprocess
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - pip
  - numpy
  - matplotlib
  - scikit-image
  - scikit-learn
  - pystackreg
  - czifile
  - jupyter
  - trackpy
  - numba
